# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.state.com:
  peer0.retail.state.com:
  peer0.firearmsManu.state.com:
  peer0.police.state.com:
  peer0.ncis.state.com:
  peer0.usgovt.state.com:
  peer0.medic.state.com:

networks:
  byfn:
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-retail
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.retail.state.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/ff52fe76de77060951f85f1f2d7bacf065312681b495ad8e3e101b25bcf895ee_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.retail.state.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/ff52fe76de77060951f85f1f2d7bacf065312681b495ad8e3e101b25bcf895ee_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/retail.state.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerretail
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-firearmsManu
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.firearmsManu.state.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/c5ffcca005817cf364d1a5a3abaf5e3ff7a21779ab06f3f2ddaa6cb60aad64f3_sk
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.firearmsManu.state.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/c5ffcca005817cf364d1a5a3abaf5e3ff7a21779ab06f3f2ddaa6cb60aad64f3_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/firearmsManu.state.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerfirearmsManu
    networks:
      - byfn

 ca2:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-police
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.police.state.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/7f7f62c7510311c9e6e2a3f1fa31a13c47e450cc3e68dae5700427c457bd92f0_sk
    ports:
      - "10054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.police.state.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/7f7f62c7510311c9e6e2a3f1fa31a13c47e450cc3e68dae5700427c457bd92f0_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/police.state.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerpolice
    networks:
      - byfn
      
 ca3:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-ncis
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.ncis.state.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/b2211644641d42254ac297f5726cefd6556cd19529c495b90025732dff27bb95_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.ncis.state.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/b2211644641d42254ac297f5726cefd6556cd19529c495b90025732dff27bb95_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/ncis.state.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerncis
    networks:
      - byfn

 ca4:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-usgovt
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.usgovt.state.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/4c335ac2fa388cb2cb80bb95341453e46753434f7f432988b7827309c52525f8_sk
    ports:
      - "12054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.usgovt.state.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/4c335ac2fa388cb2cb80bb95341453e46753434f7f432988b7827309c52525f8_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/usgovt.state.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerusgovt
    networks:
      - byfn

 ca5:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-medic
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.medic.state.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/39b930ec704835f755da5e5f020bdd256b7b45fbdc1f638860f936251b7eea7a_sk
    ports:
      - "11054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.medic.state.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/39b930ec704835f755da5e5f020bdd256b7b45fbdc1f638860f936251b7eea7a_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/medic.state.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peermedic
    networks:
      - byfn

  orderer.state.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.state.com
    container_name: orderer.state.com
    networks:
      - byfn

  peer0.retail.state.com:
    container_name: peer0.retail.state.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.retail.state.com
    networks:
      - byfn

  peer0.firearmsManu.state.com:
    container_name: peer0.firearmsManu.state.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.firearmsManu.state.com
    networks:
      - byfn

  peer0.police.state.com:
    container_name: peer0.police.state.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.police.state.com
    networks:
      - byfn

  peer0.ncis.state.com:
    container_name: peer0.ncis.state.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.ncis.state.com
    networks:
      - byfn

  peer0.usgovt.state.com:
    container_name: peer0.usgovt.state.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.usgovt.state.com
    networks:
      - byfn

  peer0.medic.state.com:
    container_name: peer0.medic.state.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.medic.state.com
    networks:
      - byfn


